src/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LogoutView
from core.views import LoginRuView, PasswordRuResetView


admin.site.index_title = 'Rompas administration'


urlpatterns = [
    path('boss/', admin.site.urls),
    re_path(r'', include(('rompas.urls', 'rompas'), namespace='rompas')),
    url(r'^login/',
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name='login'),
    url(r'^ru/login/',
        LoginRuView.as_view(redirect_authenticated_user=True),
        name='login'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout', ),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    re_path('^ru/accounts/password_reset/', PasswordRuResetView.as_view(), name='password_reset_ru'),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('orders.urls', 'orders'), namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
admin.site.site_header = "Rompas Administration"
admin.site.site_title = "Rompas Admin Portal"
admin.site.index_title = "Rompas Administration"

src/rompas/urls.py
from django.urls import re_path
from django.conf.urls import url
import django.views.defaults
from . import views

urlpatterns = [
    url(r'^cart_form/$', views.cart_form, name='cart_form'),
    url(r"^subscription/(?P<subscription_name>.[\w-]+[']*)/$", views.subscription, name='subscription'),
    url(r"^subscription_update/(?P<subscription_name>.[\w-]+[']*)/$", views.subscription_update, name='subscription_update'),
    url(r"^cancel_subscription/$", views.cancel_subscription, name='cancel_subscription'),
    url(r"^tokens/(?P<tokens_name>.[\w-]+[']*)/$", views.add_tokens, name='add_tokens'),
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^help/$', views.help, name='help'),
    url(r'^help-send/$', views.help_send, name='help_send'),
    url(r"^library/(?P<category_slug>.[\w-]+[']*)/$", views.library_category, name='library_category'),
    url(r'^private_policy/$', views.private_policy, name='private_policy'),
    url(r'^terms_of_use/$', views.terms_of_use, name='terms_of_use'),
    re_path(r'^profile/$', views.profile, name='profile'),
    re_path(r'^profile/history$', views.purchase_history, name='purchase_history'),
    url(r"^profile/history/(?P<category_slug>.[\w-]+[']*)/$", views.purchase_history_category, name='purchase_history_category'),
    re_path(r'^sign_in/$', views.signin, name='sign_in'),
    re_path(r"^buy_sub/(?P<sub_name>.[\w-]+[']*)/$", views.buy_sub, name='buy_sub'),
    url(r'^pay-callback/$', views.PayCallbackView.as_view(), name='pay_callback'),
    url(r'^ru/$', views.index_ru, name='index_ru'),
    url(r'^ru/about/$', views.about_ru, name='about_ru'),
    url(r'^ru/faq/$', views.faq_ru, name='faq_ru'),
    url(r'^ru/help/$', views.help_ru, name='help_ru'),
    url(r'^ru/help-send/$', views.help_send_ru, name='help_send_ru'),
    url(r"^ru/library/(?P<category_slug>.[\w-]+[']*)/$", views.library_category_ru, name='library_category_ru'),
    url(r'^ru/private_policy/$', views.private_policy_ru, name='private_policy_ru'),
    url(r'^ru/terms_of_use/$', views.terms_of_use_ru, name='terms_of_use_ru'),
    re_path(r'^ru/profile/$', views.profile_ru, name='profile_ru'),
    re_path(r'^ru/profile/history$', views.purchase_history_ru, name='purchase_history_ru'),
    url(r"^ru/profile/history/(?P<category_slug>.[\w-]+[']*)/$", views.purchase_history_category_ru,
        name='purchase_history_category_ru'),
    re_path(r'^ru/sign_in/$', views.signin_ru, name='sign_in_ru'),
    url(r'^boss/rompas/(?P<order_id>\d+)/$', views.AdminOrderDetail, name='AdminOrderDetail'),
    url(r'^test/$', views.test, name='test'),
]

src/rompas/models.py
from django.db import models
from django.contrib.auth.models import User
from core.models import BaseModel
import datetime
from django.utils.translation import gettext as _
from dateutil.relativedelta import relativedelta
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
import re
from transliterate import translit
from transliterate.exceptions import LanguageDetectionError


def transliterate(text):
    pieces = str(re.sub('[\W]+', ' ', text)).lower().split(' ')
    result = []

    for piece in pieces:
        try:
            result.append(translit(piece, reversed=True))
        except LanguageDetectionError:
            result.append(piece)
    return '-'.join([r for r in result if r])


class Currency(BaseModel):
    name = models.CharField(
        max_length=16,
        unique=True,
        verbose_name=_('Name'),
    )

    symbol = models.ImageField(verbose_name='Sybmol', null=True, blank=True)

    def __str__(self):
        return self.name


class MainCategory(models.Model):
    name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name'),
    )

    name_ru = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name Ru'),
    )

    photo = models.ImageField(verbose_name='Photo', null=True, blank=True)

    photo_ru = models.ImageField(verbose_name='Photo Ru', null=True, blank=True)

    description = models.TextField(
        max_length=2000,
        verbose_name=_('Description'),
        blank=True,
        null=True,
    )

    description_ru = models.TextField(
        max_length=2000,
        verbose_name=_('Description Ru'),
        blank=True,
        null=True,
    )

    slug = models.CharField(
        max_length=150,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    def cat(self):
        return Category.objects.filter(main_category_id=self.id)

    def __str__(self):
        return self.name


class Subscription(models.Model):
    name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name'),
    )

    name_ru = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name Ru'),
    )

    price = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Price'),
    )

    slug = models.CharField(
        max_length=150,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    token = models.IntegerField(verbose_name=_('Token'), null=True)

    def __str__(self):
        return self.name


class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_('User'))
    subscription = models.ForeignKey(Subscription,
                                     null=True,
                                     blank=True,
                                     on_delete=models.SET_NULL,
                                     verbose_name=_('Subscription'),
                                     )

    subscription_end = models.DateTimeField(
        verbose_name='Subscription ends',
        null=True,
        blank=True
    )

    tokens_left = models.IntegerField(blank=True, null=True, verbose_name=_('Tokens Left'), default=0)

    slug = models.CharField(
        max_length=150,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    name = models.CharField(verbose_name='Name', max_length=150, null=True, blank=True)

    bonus = models.BooleanField(default=False)

    email_subscription = models.BooleanField(default=True, verbose_name=_('Email subscription'))

    subscription_active = models.BooleanField(default=False, verbose_name=_('Subscription active'))

    def save(self, *args, **kwargs):
        self.slug = transliterate(self.user.username)
        super(Profile, self).save(*args, **kwargs)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
        instance.profile.save()

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name'),
    )

    name_ru = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name Ru'),
    )

    slug = models.CharField(
        max_length=150,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    main_category = models.ForeignKey(MainCategory,
                                      null=True,
                                      on_delete=models.PROTECT,
                                      verbose_name=_('Main Category'),
                                      )

    def sub(self):
        return SubCategory.objects.filter(category_id=self.id)

    def __str__(self):
        return self.name + ' - ' + self.main_category.name


class SubCategory(models.Model):
    name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name'),
    )

    name_ru = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name Ru'),
    )

    slug = models.CharField(
        max_length=150,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    category = models.ForeignKey(Category,
                                 null=True,
                                 on_delete=models.PROTECT,
                                 verbose_name=_('Category'),
                                 )

    def __str__(self):
        return self.name + ' - ' + self.category.name + ' - ' + self.category.main_category.name


class Product(BaseModel):
    name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name'),
    )

    name_ru = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name Ru'),
    )

    slug = models.CharField(
        max_length=150,
        blank=True,
        verbose_name=_('Slug'),
        help_text="Don't touch it!"
    )

    description = models.TextField(
        max_length=2000,
        verbose_name=_('Description'),
        blank=True,
        null=True,
    )

    description_ru = models.TextField(
        max_length=2000,
        verbose_name=_('Description Ru'),
        blank=True,
        null=True,
    )

    category = models.ForeignKey(SubCategory,
                                 null=True,
                                 on_delete=models.PROTECT,
                                 verbose_name=_('Category'),
                                 )

    currency = models.ForeignKey(Currency,
                                 null=True,
                                 on_delete=models.SET_NULL,
                                 verbose_name=_('Currency'),
                                 )

    url = models.CharField(
        max_length=512,
        blank=True,
        null=True,
        verbose_name=_('Url'),
    )

    you_tube = models.URLField(verbose_name=_('You_Tube, Only Assets'), blank=True, null=True)

    file_size = models.IntegerField(verbose_name=_('Size'), default=0)

    main_photo = models.ImageField(verbose_name='Main Photo')

    price = models.IntegerField(verbose_name=_('Price'))

    old_price = models.IntegerField(null=True, blank=True, verbose_name=_('Old Price'),)

    file = models.FileField(null=True, blank=True)

    def image(self):
        return Image.objects.filter(product_id=self.id)

    def __str__(self):
        return self.name


class Image(models.Model):
    product = models.ForeignKey(Product,
                                null=True,
                                on_delete=models.CASCADE,
                                verbose_name=_('Product'),
                                )

    photo = models.ImageField(verbose_name='Photo', null=True, blank=True)

    def __str__(self):
        return self.product.name


class BuyHistory(models.Model):
    user = models.ForeignKey(User,
                             null=True,
                             on_delete=models.CASCADE,
                             verbose_name=_('User'),
                             )

    product = models.ForeignKey(Product,
                                null=True,
                                on_delete=models.CASCADE,
                                verbose_name=_('Product'),
                                )

    date = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Purchased at'),
        null=True
    )

    def __str__(self):
        return self.user.username


class PagesPhoto(models.Model):
    name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name'),
    )

    photo = models.ImageField(verbose_name='Photo', null=True, blank=True)

    photo_ru = models.ImageField(verbose_name='Photo ru', null=True, blank=True)

    active = models.BooleanField(default=False)

    top = models.BooleanField(default=False)

    left = models.BooleanField(default=False)

    right = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class ArticleCategory(models.Model):
    name = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name'),
    )

    name_ru = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name=_('Name Ru'),

src/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

src/rompas/templates/rompas/about.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}About{% endblock %}
{% block content %}
<section class="hero-area">
    <div class="block z-index-10">
		<h1>About</h1>
	</div>
</section>
<br>
<section>
    <section class="py-0">
        <div class="container">
            <p>Rompas.com.ua is a website that offers a library of materials and finished collections for your projects and your creativity. We only have quality textures and materials. We are created to give you the opportunity to put your idea into practice.</p>
            <br>
            <h4>The goods that our company provides:</h4>
            <br>
            <p>Assets - is a ready assembly of models and materials for creating games and other projects that can  combine both game models and materials and textures.</p>
            <br>
            <p>3d scans - are scanned objects using photogrammetry, which include the object and texture maps.</p>
            <br>
            <p>PBR materials - is a finished material, which includes such maps as color map, map of normal, height maps, reflections and others. </p>
            <br>
            <p>Phototextures -are tile textures, or satin textures, that are made with the camera.</p>
            <br>
            <h4>Payment:</h4>
            <br>
            <p>On our website at the moment you can pay with LIQPAY.</p>
            <br>
            <h4>Return:</h4>
            <br>
            <p>You have the right to claim compensation, but it is always subject to the condition that you notify Rompas.com of the loss and/or damage in writing within a period not exceeding one month from its discovery.</p>
            <br>
            <p>Reimbursements are made to an individual's card</p>
            <br>
            <p>Are you an indie developer? Then you have come to the right place. Here you will find a lot of assets that will make it much easier for you to implement your project and bring your idea to life!</p>
        </div>
    </section>
</section>
{% block footer %}
{% include 'core/footer.html' %}
{% endblock %}
{% endblock %}

src/rompas/templates/rompas/buy_sub.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Rompas{% endblock %}
{% block content %}
<section class="hero-area">
    <div class="block z-index-10">
		<h1>Thank you {{ user.username }} for choosing us, now you need pay for the subscription.</h1>
        <form method="post" action="https://www.liqpay.ua/api/3/checkout/" accept-charset="utf-8">
            <input type="hidden" name="data" value="{{ data }}"/>
            <input type="hidden" name="signature" value="{{ signature }}"/>
            <button style="border: none !important; display:inline-block !important;text-align: center !important;padding: 7px 20px !important; color: #fff !important; font-size:16px !important; font-weight: 600 !important; font-family:OpenSans, sans-serif; cursor: pointer !important; border-radius: 2px !important; background: rgb(122,183,43) !important;"onmouseover="this.style.opacity='0.5';" onmouseout="this.style.opacity='1';">
                <img src="https://static.liqpay.ua/buttons/logo-small.png" name="btn_text" style="margin-right: 7px !important; vertical-align: middle !important;"/>
                <span style="vertical-align:middle; !important">Buy</span>
            </button>
        </form>
	</div>
</section>
{% endblock %}

src/rompas/templates/rompas/help.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Help{% endblock %}
{% block content %}
<section class="hero-area">
	<div class="block z-index-10">
		<h1>Help</h1>
	</div>
</section>
<br>
<section id="contact-us" class="contact-us section-bg">
	<div class="container">
		<div class="row">
			<div class="title text-center wow fadeIn" data-wow-duration="500ms">
				<h2>Get In <span class="color">Touch</span></h2>
				<div class="border"></div>
			</div>
			<div class="contact-info col-md-6 wow fadeInUp" data-wow-duration="500ms">
				<h3>Contact Details</h3>
				<div class="contact-details">
					<div class="con-info clearfix">
						<i class="tf-ion-ios-telephone-outline"></i>
						<span>Phone: +380937817413</span>
					</div>

					<div class="con-info clearfix">
						<i class="tf-ion-ios-email-outline"></i>
						<span>Email: Rompasstudio@gmail.com</span>
					</div>
				</div>
			</div>
			<div class="contact-form col-md-6 wow fadeInUp" data-wow-duration="500ms" data-wow-delay="300ms">
				<form id="contact-form" method="post">
					{% csrf_token %}
					<div class="form-group">
						<input type="text" placeholder="Your Name" class="form-control" name="name" id="id_name" required="" maxlength="64">
					</div>
					<div class="form-group">
						<input type="email" placeholder="Your Email" class="form-control" name="email" id="id_email" maxlength="64" required="">
					</div>
					<div class="form-group">
						<textarea cols="40" rows="10" maxlength="2000" required="" placeholder="Message" class="form-control" name="message" id="id_message"></textarea>
					</div>
					<div id="mail-success" class="success">
						Thank you. The Mailman is on His Way :)
					</div>
					<div id="mail-fail" class="error">
						Sorry, don't know what happened. Try later :(
					</div>
					<div id="cf-submit">
						<input type="submit" id="contact-submit" class="btn btn-transparent" value="Submit">
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
{% block footer %}
{% include 'core/footer.html' %}
{% endblock %}
{% endblock %}

src/rompas/templates/rompas/library-category.html
{% extends 'core/base.html' %}
{% load static %}
{% load rompas_extras %}
{% block title %}Library{% endblock %}
{% block extra_css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    p {color: #afbac4}
</style>
{% endblock %}
{% block content %}
<div class="flex">
    <div class="sidenav">
        <input class="form-control search-library icon opacity-05" id="search" name="search" type="text" maxlength="128" oninput="Search()" placeholder="Search" aria-label="Search">
        {% for category in categories %}
            {% if category == active_category %}
                <button class="dropdown-btn active">{{ category.name }}
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container" style="display: block">
                    <a onclick="Category('{{ category.name|cut:" " }}')" id="{{ category.name }}">All</a>
                    {% for cat in category.cat %}
                    <button class="dropdown-btn">{{ cat.name }}
                        <i class="fa fa-caret-down"></i>
                    </button>
                    <div class="dropdown-container">
                        <a onclick="Category('{{ category.name|cut:" " }}{{ cat.name|cut:" " }}')" class="left-35">All</a>
                        {% for subcategory in cat.sub %}
                            <a onclick="Category('{{ category.name|cut:" " }}{{ cat.name|cut:" " }}{{ subcategory.name|cut:" " }}')" class="left-35">{{ subcategory.name }}</a>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
            {% else %}
                <button class="dropdown-btn">{{ category.name }}
                    <i class="fa fa-caret-down"></i>
                </button>
                <div class="dropdown-container">
                    <a onclick="Category('{{ category.name|cut:" " }}')">All</a>
                        {% for cat in category.cat %}
                            <button class="dropdown-btn">{{ cat.name }}
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="dropdown-container">
                                <a onclick="Category('{{ category.name|cut:" " }}{{ cat.name|cut:" " }}')" class="left-35">All</a>
                                {% for subcategory in cat.sub %}
                                    <a onclick="Category('{{ category.name|cut:" " }}{{ cat.name|cut:" " }}{{ subcategory.name|cut:" " }}')" class="left-35">{{ subcategory.name }}</a>
                                {% endfor %}
                            </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="library">
        {% for product in products %}
        <div style="display: none" class="{{ product.name }} product {{ product.category.category.main_category.name|cut:" " }} {{ product.category.category.main_category.name|cut:" " }}{{ product.category.category.name|cut:" " }} {{ product.category.category.main_category.name|cut:" " }}{{ product.category.category.name|cut:" " }}{{ product.category.name|cut:" " }}">
            <div class="block2">
                <div class="block2-img wrap-pic-w of-hidden pos-relative">
                    <div class="img-hover-zoom--brightness photo">
                        <a data-remodal-target="{{ product.id }}" href="#!">
                            <img src="{{ product.main_photo.url }}" alt="IMG-PRODUCT" class="width-100">
                            <div class="carousel-caption price-title product_price" style="background-color: #292F36; opacity: 1">
                                <h4 align="left" class="search product_name" style="font-size: 14px">{{ product.name }}</h4>
                                {% if user.is_authenticated %}
                                    {% if user|download_check:product %}
                                        <a href="/profile/history" class="product_currency" align="right">
                                            <span>
                                                <img class="g-pos-rel g-top-1 g-mr-8" src="{% static 'theme/images/icon/download.png' %}" height="18px" width="18px">
                                            </span>
                                        </a>
                                    {% else %}
                                        <h4 class="product_currency" align="right">{{ product.price }} <img src="{{ product.currency.symbol.url }}" class="vertical_top" height="19px" width="19px"></h4>
                                    {% endif %}
                                {% else %}
                                    <h4 class="product_currency" align="right">{{ product.price }} <img src="{{ product.currency.symbol.url }}" class="vertical_top" height="18px" width="18px" ></h4>
                                {% endif %}
                            </div>
                        </a>
                        <a href="" class="block2-btn-addwishlist hov-pointer trans-0-4">
                            <i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
                            <i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% for product in products %}
<div class="remodal remodal-70" data-remodal-id="{{ product.id }}" style="width: 80%">
    <button class="remodal-close" data-remodal-action="close"></button>
    <h1>{{ product.name }}</h1>
    <h2>{{ product.category }}</h2>
    <div class="main object_contain">
        {% if product.category.category.main_category_id == 1 %}
        <div class="block2">
            <div class="slider slider-for">
                {% for image in product.image %}
                <div class="block2-img wrap-pic-w of-hidden pos-relative">
                    <img src="{{ image.photo.url }}" alt="IMG-PRODUCT" class="inline_d center" style="height: auto; width: auto">
                </div>
                {% endfor %}
                {% if product.you_tube %}
                <div class="you_tube">
                    <iframe src="{{ product.you_tube }}" width="100%" height="100%" allow="autoplay; encrypted-media" allowfullscreen></iframe>
                 </div>
                {% endif %}
            </div>
        </div>
        <br>
        <div class="slider slider-nav">
            {% for image in product.image %}
            <div>
                <img src="{{ image.photo.url }}" alt="IMG-PRODUCT" class="inline_d center">
            </div>
            {% endfor %}
            {% if product.you_tube %}
            <div>
                <img src="{% static '/theme/images/video.png' %}" alt="IMG-PRODUCT" class="width-100 center">
            </div>
            {% endif %}
        </div>
        {% else %}
        <div class="block2">
            <div class="slider vertical-center">
                {% for image in product.image %}
                <div class="block2-img wrap-pic-w of-hidden pos-relative">
                    <img src="{{ image.photo.url }}" alt="IMG-PRODUCT" class="inline_d center">
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
    <div class="container remodal_text">
        <div class="price-title" style="background-color: #292F36; opacity: 1">
            <p class="left_50"><strong class="value">{{ product.price }} <img src="{{ product.currency.symbol.url }}" class="remodal_currency"></strong></p>
            <p class="right_50"><strong class="value">{{ product.file_size }} mb</strong></p>
        </div>
        <div class="price-title padding-20" style="background-color: #292F36; opacity: 1">
            <br>
            <p> {{ product.description|linebreaks }}</p>
            {% if product.url %}
                <a href="{{ product.url }}" class="btn" style="background-color: #353b43" target="_blank">Get it on Unity Asset Store</a>
            {% endif %}
        </div>
        <br>
        {% if product.currency_id == 1 %}
        <form id="myForm{{ product.id }}"  action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
            <div class="flex-m flex-w p-t-10">
                <div class="rs2-select2 rs3-select2 bo4 of-hidden w-size16">
                    <select class="selection-2 none_d" name="quantity" id="id_quantity">
                        <option value="1" selected>1</option>
                    </select>
                    <input type="hidden" name="update" value="False" id="id_update">
                </div>
            </div>
        {% csrf_token %}
        {% if user.is_authenticated %}
            {% if user|download_check:product %}
                <a href="{{ product.file.url }}" class="btn btn-lg download">Download</a>
            {% else %}
                <button type="submit" class="btn btn-lg add_to_cart">Add to cart</button>
            {% endif %}
        {% else %}
                <button type="submit" class="btn btn-lg add_to_cart">Add to cart</button>
        {% endif %}
        </form>
        {% else %}
            {% if user.is_authenticated %}
                {% if user|download_check:product %}
                    <a href="{{ product.file.url }}" class="btn btn-lg download">Download</a>
                {% else %}
                    {% if user.profile.tokens_left >= product.price %}
                        <form method="post">
                            {% csrf_token %}
                            <select name="user" required="" id="id_user" class="none_d">
                                <option value="{{ user.id }}" selected="">{{ user.username }}</option>
                            </select>
                            <select name="product" required="" id="id_product" class="none_d">
                                <option value="{{ product.id }}" selected="">{{ product.name }}</option>
                            </select>
                            <button type="submit" class="btn btn-lg add_to_cart">Buy</button>
                        </form>
                    {% else %}
                        <a href="/profile" class="btn btn-lg add_to_cart">Not enough tokens</a>
                    {% endif %}
                {% endif %}
            {% else %}
                <a href="/login" class="btn btn-lg add_to_cart">Buy</a>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endfor %}
{% endblock %}
{% block extra_js %}
<script>
    window.onload = function() {
      Category('{{ active_category.name|cut:" " }}');
    };
</script>
{% endblock %}

src/rompas/templates/rompas/test.html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

</body>
</html>